name: github-actions
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: { }

jobs:
  run-sdk-tester:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run sdk tester
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          cd demo
          ./setup
          python3 main.py
      - name: Post to a Slack channel
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'C03U3TD1MA5'
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\nLog: ${{ github.server_url }}/${{ github.repository }}/runs/${{ github.run_id }}?check_suite_focus=true"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
