name: github-actions
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '15 5,22 * * *'

jobs:
  run-sdk-tester:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run sdk tester
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          cd demo
          ./setup
          python3 main.py
