name: production
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run this 12:00 UTC every day
    - cron: '0 12 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: { }

jobs:
  build-sdk-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build sdk containers
        run: |
          cd demo
          ./setup

  run-sdk-tester:
    needs: build-sdk-containers
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        language: [ 'node', 'php', 'python', 'ruby', 'csharp', 'java' ]
    steps:
      - uses: actions/checkout@v3
      - name: run sdk tester
        env:
          API_KEY: ${{ secrets.API_KEY }}
          LANGUAGE: ${{ matrix.language }}
          SERVER: 'api.hellosign.com'
        run: |
          cd demo
          python3 main.py
      - name: Post to a Slack channel
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # 'C030GQLB41L' for #alerts-eng-hs-api-notifications, 'C03U3TD1MA5' for #test-slackbot
          channel-id: 'C03U3TD1MA5'
          # For posting a simple plain text message
          slack-message: "SDK tester result: ${{ job.status }}\nLog: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
