name: staging
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run this 12:00 UTC every day
    - cron: '0 12 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: { }

jobs:
  run-sdk-tester:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'node', 'php', 'python', 'ruby', 'csharp', 'java' ]
    steps:
      - uses: actions/checkout@v3
      - name: run sdk tester
        env:
          API_KEY: ${{ secrets.API_KEY }}
          LANGUAGE: ${{ matrix.language }}
          SERVER: 'api.staging-hellosign.com'
        run: |
          ./build ${{ matrix.language }}
          cd demo
          python3 main.py

  notifiy-slack:
    needs: run-sdk-tester
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # 'C030GQLB41L' for #alerts-eng-hs-api-notifications, 'C03U3TD1MA5' for #test-slackbot
          channel-id: 'C03U3TD1MA5'
          # For posting a simple plain text message
          slack-message: "Staging SDK tester result: ${{ needs.run-sdk-tester.result }}\nLog: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}